# Generated by Django 3.0.7 on 2020-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_title', models.CharField(default='', max_length=500)),
                ('blog_heading', models.CharField(default='', max_length=500)),
                ('blog_description', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
