# Generated by Django 3.0.7 on 2020-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_auto_20200618_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('CustomerName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_profile', models.CharField(default='N', max_length=1)),
                ('phone', models.IntegerField(default='', max_length=15)),
                ('issue', models.CharField(default='', max_length=5000)),
                ('address', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
