# Generated by Django 3.0.7 on 2020-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0003_customerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
