# Generated by Django 3.0.7 on 2020-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0005_auto_20200627_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='address',
            new_name='seller_address',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='shipping_data',
            field=models.CharField(default='', max_length=500),
        ),
    ]
