# Generated by Django 3.0.7 on 2020-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0006_auto_20200627_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='cust_id',
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='email',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
