# Generated by Django 3.0.7 on 2020-06-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0007_auto_20200627_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='shipping_data',
            new_name='shipping_address',
        ),
    ]
