# Generated by Django 3.0.7 on 2020-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0008_auto_20200627_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
