# Generated by Django 3.0.7 on 2020-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0009_auto_20200627_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=70)),
                ('state', models.CharField(default='', max_length=70)),
                ('zip_code', models.CharField(default='', max_length=10)),
                ('prod_list', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
