# Generated by Django 3.0.7 on 2020-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('order_id', models.IntegerField(default='', max_length=100)),
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
