# Generated by Django 3.0.7 on 2020-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0011_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
